package rain_information;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class EditRainInformation extends javax.swing.JPanel {

    //  Variables for SQL and connection to database
    Statement statement;
    PreparedStatement pst;
    Connection connection;
    ResultSet resultSet;
    String tableString = "rds_db1.plant_info";
    String SQL;

    String[] column = {"date", "measurement_mm"};

//    Data Variables
    Date date;
    float rain_mm;

    public EditRainInformation(Connection connection) {
        initComponents();
        this.connection = connection;
        doConnect();
    }

    final void doConnect() {

//        'finally' runs regardless of whether an exception is thrown,
//        so the statements and result set are always closed
//        !!!!!!!!!!!!CLOSE all the connections to avoid the too many connections error!!!!!!!!!!!!!
        try {

            SQL = "SELECT * FROM " + tableString;

            statement = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            
            resultSet = statement.executeQuery(SQL);

        } catch (SQLException error) {
            System.out.println("addPlant" + error.getMessage());

        }
    }

    public java.sql.Date convertJavaDateToSqlDate(java.util.Date date) {
        return new java.sql.Date(date.getTime());
    }

    void getData() {
        date = convertJavaDateToSqlDate(dateOfPlantingDateChooser.getDate());
        rain_mm = Float.parseFloat(rain_mm_textField.getText());
    }

    boolean isValidated() {
        return true;
    }

    void setValues(ResultSet resultSet, String id) {
        try {
            if (resultSet.next()) {
                dateOfPlantingDateChooser.setDate(resultSet.getDate(column[1]));
                rain_mm_textField.setText(Float.toString(resultSet.getFloat(column[2])));
            }

        } catch (SQLException e) {
            System.out.print("set value error: " + e);
        }
    }

    void editData() {
        if (isValidated()) {
            try {
                statement = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,
                        ResultSet.CONCUR_UPDATABLE);
                String SQL = "SELECT * FROM " + tableString;
                resultSet = statement.executeQuery(SQL);

                String query = ("UPDATE " + tableString + " SET `" 
                        + column[1] + "` = '" + date + "'," + "`" 
                        + column[2] + "` = '" + rain_mm + "';");
                System.out.println(query);
                pst = connection.prepareStatement(query);
                pst.executeUpdate();

            } catch (SQLException error) {
                System.out.println("edit data| " + error);

            } finally {
                try {
                    resultSet.close();
                } catch (SQLException error) {
                    System.out.println(error);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "invalid data entered");
        }
    }

    void clear() {
        dateOfPlantingDateChooser.setDate(null);
        rain_mm_textField.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        rain_mm_textField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateOfPlantingDateChooser = new com.toedter.calendar.JDateChooser();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(39, 45, 54));

        confirmButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(0, 0, 0));
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(0, 0, 0));
        cancelButton.setText("Clear");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        rain_mm_textField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rain_mm_textField.setForeground(new java.awt.Color(0, 0, 0));
        rain_mm_textField.setMargin(new java.awt.Insets(0, 2, 0, 0));
        rain_mm_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rain_mm_textFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rain (mm)");

        dateOfPlantingDateChooser.setForeground(new java.awt.Color(0, 0, 0));
        dateOfPlantingDateChooser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateOfPlantingDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(rain_mm_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(confirmButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton)))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateOfPlantingDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rain_mm_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(confirmButton))
                .addGap(23, 23, 23))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        getData();
        editData();
        clear();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void rain_mm_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rain_mm_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rain_mm_textFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private com.toedter.calendar.JDateChooser dateOfPlantingDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField rain_mm_textField;
    // End of variables declaration//GEN-END:variables
}
